spring.application.name=Log
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.elasticsearch.uris=http://localhost:9200


app.redis.stream.key=log-events
app.redis.stream.group=log-processors
app.redis.stream.workers=3